# Config file for using the update script

# THESE VALUES MUST BE ADDRESSED
private_code  : "28pT34hJdIppodtKd97K9MwNqn0AjBdt"
server_token  : "QIKzedUbeVquGjofcyjQ7VQiO7sB2TDZ"

hide_defaults : true
delete_old    : true



# FILE PATHS
server_loc  : "/home/unrealpugs/LinuxServer"

data_path   : "__default__"
log_path    : "update_log.log"
cache_path  : "cache.txt"
references  : "references.txt"

pak_dir_ext : "UnrealTournament/Content/Paks/"
ini_ext     : "UnrealTournament/Saved/Config/LinuxServer/Game.ini"
ruleset_ext : "UnrealTournament/Saved/Config/Rulesets/rulesets.json"


# ADVANCED OPTIONS
allowed_rulesets : ""

# AUTOMATION OPTIONS
start_command    : "/home/unrealpugs/startscript.sh"
ut_process_name  : "UE4Server-Linux-Shipping"
