# Config file for using the update script

# THESE VALUES MUST BE ADDRESSED
private_code  : ""
server_token  : ""
hide_defaults : true
delete_old    : false



# FILE PATHS
server_loc  : "/home/unrealpugs/LinuxServer"

log_path    : "Data/update_log.log"
cache_path  : "Data/cache.txt"
references  : "Data/references.txt"

pak_dir_ext : "UnrealTournament/Content/Paks/"
ini_ext     : "UnrealTournament/Saved/Config/LinuxServer/Game.ini"
ruleset_ext : "UnrealTournament/Saved/Config/Rulesets/rulesets.json"


# ADVANCED OPTIONS
start_command    : "/home/unrealpugs/startscript.sh"
ut_process_name  : "UE4Server-Linux-Shipping"
allowed_rulesets : ""
